version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: monthly }
    groups: { npm: { patterns: ['*'] } }
    versioning-strategy: increase
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: monthly }
    groups: { github-action: { patterns: ['*'] } }
