/**
 * Syncs the canonical VersaTiles container specification into the docs.
 *
 * The specification lives in its own repository so that implementers outside
 * this project can cite it and its design discussions stay in one place:
 *   https://github.com/versatiles-org/versatiles-spec
 *
 * This script is the only writer of `compendium/specification_container.md`.
 * The generated files are committed, so builds need no network access and an
 * upstream change arrives as a reviewable diff rather than a silent deploy.
 *
 *   npm run sync:spec            # pull the current specification
 *   npm run sync:spec -- --check # fail if upstream has moved on
 *   npm run sync:spec -- --branch=some-draft
 */

import { existsSync, readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';
import { fileURLToPath } from 'url';
import * as prettier from 'prettier';

const ROOT = resolve(fileURLToPath(import.meta.url), '../..');

const SPEC = {
	repo: 'versatiles-org/versatiles-spec',
	branch: 'main',
	/** Specification document inside the repository. */
	doc: 'v02/readme.md',
	/** Images referenced by the document, resolved next to it. */
	images: ['file_format.svg', 'level_blocks.svg', 'block_tiles.svg'],
};

/** Where the rendered page and its images land in this repository. */
const TARGET_DOC = 'compendium/specification_container.md';
const TARGET_IMAGE_DIR = 'assets';
/** Image files are prefixed so they do not collide with other assets. */
const IMAGE_PREFIX = 'container_';
/** Path used from inside the generated page to reach the images. */
const IMAGE_HREF_DIR = '../assets';

interface Options {
	check: boolean;
	branch: string;
}

function parseArgs(argv: string[]): Options {
	const branchArg = argv.find((a) => a.startsWith('--branch='));
	return {
		check: argv.includes('--check'),
		branch: branchArg ? branchArg.slice('--branch='.length) : SPEC.branch,
	};
}

function rawUrl(branch: string, path: string): string {
	return `https://raw.githubusercontent.com/${SPEC.repo}/${branch}/${path}`;
}

async function fetchText(url: string): Promise<string> {
	const response = await fetch(url);
	if (!response.ok) throw new Error(`${response.status} ${response.statusText} for ${url}`);
	return response.text();
}

/** Turns the upstream document into a VitePress page. */
function render(markdown: string, branch: string): string {
	const permalink = `https://github.com/${SPEC.repo}/blob/${branch}/${SPEC.doc}`;

	// Point image references at the copies stored under assets/.
	let body = markdown;
	for (const image of SPEC.images) {
		body = body.replaceAll(`(${image})`, `(${IMAGE_HREF_DIR}/${IMAGE_PREFIX}${image})`);
	}

	// Insert a provenance note directly after the title, so readers of the
	// rendered page know where the authoritative copy is.
	const note = [
		'> [!NOTE]',
		'> This page is generated from the canonical specification in',
		`> [versatiles-spec](https://github.com/${SPEC.repo}). Report problems and propose changes there;`,
		'> edits made here are overwritten.',
		'>',
		`> Source: [\`${SPEC.doc}\`](${permalink}).`,
	].join('\n');

	const lines = body.split('\n');
	const titleIndex = lines.findIndex((line) => line.startsWith('# '));
	if (titleIndex === -1) throw new Error('specification has no top-level heading');
	lines.splice(titleIndex + 1, 0, '', note);

	const banner = `<!-- Generated by scripts/sync-spec.ts from ${SPEC.repo} — do not edit. -->`;
	return [banner, '', ...lines].join('\n');
}

async function main(): Promise<void> {
	const { check, branch } = parseArgs(process.argv.slice(2));

	const markdown = await fetchText(rawUrl(branch, SPEC.doc));
	const rendered = render(markdown, branch);

	const prettierConfig = await prettier.resolveConfig(resolve(ROOT, TARGET_DOC));
	const formatted = await prettier.format(rendered, { ...prettierConfig, parser: 'markdown' });

	const imageDir = SPEC.doc.replace(/[^/]+$/, '');
	const images = await Promise.all(
		SPEC.images.map(async (image) => ({
			path: `${TARGET_IMAGE_DIR}/${IMAGE_PREFIX}${image}`,
			content: await fetchText(rawUrl(branch, `${imageDir}${image}`)),
		})),
	);

	const targets = [{ path: TARGET_DOC, content: formatted }, ...images];

	const stale = targets.filter(({ path, content }) => {
		const absolute = resolve(ROOT, path);
		return !existsSync(absolute) || readFileSync(absolute, 'utf8') !== content;
	});

	if (check) {
		if (stale.length === 0) {
			console.log(`specification is in sync with ${SPEC.repo}`);
			return;
		}
		console.error(`Specification copy differs from ${SPEC.repo}@${branch}:`);
		for (const { path } of stale) console.error(`  ${path}`);
		console.error('Run `npm run sync:spec` and commit the result.');
		process.exit(1);
	}

	for (const { path, content } of targets) writeFileSync(resolve(ROOT, path), content);
	console.log(
		stale.length === 0
			? `specification already up to date (${SPEC.repo}@${branch})`
			: `updated ${stale.length} file(s) from ${SPEC.repo}@${branch}:\n` +
					stale.map(({ path }) => `  ${path}`).join('\n'),
	);
}

main().catch((error: unknown) => {
	console.error(error instanceof Error ? error.message : error);
	process.exit(1);
});
