/**
 * Renders the collected graph as a VitePress page.
 *
 * Diagrams carry no hard-coded colours: vitepress-plugin-mermaid swaps the
 * mermaid theme with the site's light and dark mode, and any colour set here
 * would survive that switch and break the contrast in one of the two.
 * Dependency kinds are therefore told apart by arrow style and by having a
 * diagram of their own.
 */

import { EDGE_KIND_META, EDGE_KINDS, type Edge, type Graph, type RepoNode } from './model';
import { CONFIG_PATH } from './config';

/** Where the machine-readable copy of the graph lives in the repository. */
const DATA_PATH = 'public/dependency-graph.json';

function repoUrl(org: string, repo: string): string {
	return `https://github.com/${org}/${repo}`;
}

function sourceUrl(org: string, edge: Edge, defaultBranch: string): string {
	const line = edge.line > 0 ? `#L${edge.line}` : '';
	return `${repoUrl(org, edge.from)}/blob/${defaultBranch}/${edge.path}${line}`;
}

/** Escapes the characters that would break out of a Markdown table cell. */
function cell(text: string): string {
	return text.replace(/\|/g, '\\|');
}

function table(headers: string[], rows: string[][]): string[] {
	return [
		`| ${headers.join(' | ')} |`,
		`| ${headers.map(() => '---').join(' | ')} |`,
		...rows.map((row) => `| ${row.join(' | ')} |`),
	];
}

/**
 * A repository can carry several tags, but a diagram box and a table section
 * can only hold it once, so the first tag wins wherever one has to be picked.
 */
function primaryTag(repo: RepoNode): string {
	return repo.tags[0] ?? '';
}

export interface RenderOptions {
	graph: Graph;
	/** Default branch per repository, for the evidence links. */
	branches: Map<string, string>;
	/** Repositories the org has but the graph leaves out, with the reason. */
	skipped: { name: string; reason: string }[];
}

export function renderPage({ graph, branches, skipped }: RenderOptions): string {
	const { org } = graph;
	const lines: string[] = [
		// The graph needs more width than the prose column allows, and the page
		// outline is what it displaces.
		'---',
		'aside: false',
		'---',
		'',
		'<!-- Generated by scripts/build-dependency-graph.ts — do not edit. -->',
		'',
		'# Repository dependencies',
		'',
		'> [!NOTE]',
		'> This page is generated from the public repositories of the',
		`> [${org}](https://github.com/${org}) organisation. To correct or extend it, change`,
		`> [\`${CONFIG_PATH}\`](https://github.com/${org}/versatiles-documentation/blob/main/${CONFIG_PATH})`,
		'> or the repository it describes — edits made here are overwritten.',
		'',
		'VersaTiles is not one program but a few dozen repositories that build on each other:',
		'a Rust core, npm packages, Docker images, tile-generation pipelines and the sites that',
		'serve the result. Those links are easy to lose track of, because they are written down',
		'in a different place every time — a `package.json` here, a `FROM` line there, a `curl`',
		'in a shell script somewhere else.',
		'',
		'This page collects all of them in one place.',
		'',
		'## Overview',
		'',
		'An arrow points **from a repository to what it depends on**, and the layout runs left to',
		'right: whatever is built on most ends up on the right, with everything that builds on it',
		'to the left. Line style says how the dependency is expressed; colour says what the',
		'repository is.',
		'',
		'A graph of the whole organisation is a lot at once, so it can be narrowed down — by one',
		'kind of dependency at a time, or to the repositories that carry a given tag. Several',
		'repositories carry more than one: versatiles-rs is both a library to build on and the',
		'tool that converts tilesets, and it shows up under either.',
		'',
		'<DependencyGraph />',
		'',
		'## Repositories',
		'',
	];

	const dependsOn = new Map<string, Set<string>>();
	const usedBy = new Map<string, Set<string>>();
	for (const edge of graph.edges) {
		if (!dependsOn.has(edge.from)) dependsOn.set(edge.from, new Set());
		if (!usedBy.has(edge.to)) usedBy.set(edge.to, new Set());
		dependsOn.get(edge.from)?.add(edge.to);
		usedBy.get(edge.to)?.add(edge.from);
	}

	const tagTitles = new Map(graph.tags.map((tag) => [tag.id, tag.title]));
	for (const tag of graph.tags) {
		const members = graph.repos.filter((repo) => primaryTag(repo) === tag.id);
		if (members.length === 0) continue;
		lines.push(`### ${tag.title}`, '', tag.summary, '');
		lines.push(
			...table(
				['Repository', 'Also', 'Description', 'Depends on', 'Used by'],
				members.map((repo) => [
					`[${repo.name}](${repoUrl(org, repo.name)})`,
					// Everything beyond the primary tag, which the heading already says.
					repo.tags
						.slice(1)
						.map((id) => tagTitles.get(id) ?? id)
						.join(', ') || '—',
					cell(repo.description ?? '—'),
					String(dependsOn.get(repo.name)?.size ?? 0),
					String(usedBy.get(repo.name)?.size ?? 0),
				]),
			),
			'',
		);
	}

	lines.push(
		'## How each link is declared',
		'',
		'A dependency can be written down in half a dozen different ways, each one found in a',
		'different kind of file. Every arrow in the graph above comes from one of the lines',
		'listed below, and can be followed back to it.',
		'',
	);

	for (const kind of EDGE_KINDS) {
		const edges = graph.edges.filter((edge) => edge.kind === kind);
		if (edges.length === 0) continue;
		const meta = EDGE_KIND_META[kind];
		lines.push(`### ${meta.title}`, '', meta.summary, '');

		lines.push(`::: details Where these ${edges.length} links come from`, '');
		lines.push(
			...table(
				['From', 'To', 'Found', 'Source'],
				edges.map((edge) => [
					edge.from,
					edge.to,
					`\`${cell(edge.detail)}\``,
					edge.path
						? `[${cell(edge.path)}](${sourceUrl(org, edge, branches.get(edge.from) ?? 'main')})`
						: `\`${CONFIG_PATH}\``,
				]),
			),
		);
		lines.push('', ':::', '');
	}

	lines.push(
		'## How this page is made',
		'',
		'`scripts/build-dependency-graph.ts` reads the public repositories of the organisation',
		'and looks for dependencies in the places they are actually declared: `package.json`,',
		'`Cargo.toml`, `Dockerfile`s, GitHub Actions workflows, and build or install scripts that',
		'fetch release assets. Markdown is deliberately not searched — README badges and prose',
		'links mention half the organisation and say nothing about what a build needs.',
		'',
		'Every arrow therefore has a file and a line behind it, listed in the tables above and',
		'available as machine-readable data in',
		// Linked at its place in the repository rather than at `/dependency-graph.json`:
		// the site serves `public/` from the root, so the published path is right for a
		// reader but resolves to nothing on disk, which is what link checking works on.
		`[\`${DATA_PATH}\`](https://github.com/${org}/versatiles-documentation/blob/main/${DATA_PATH}),`,
		'published alongside this page as `/dependency-graph.json`. What no parser can see —',
		'operational dependencies, for instance — is declared by hand in',
		`[\`${CONFIG_PATH}\`](https://github.com/${org}/versatiles-documentation/blob/main/${CONFIG_PATH}),`,
		'which is also where false positives are filtered out and repositories are assigned to',
		'the tags above.',
		'',
	);

	if (skipped.length > 0) {
		lines.push(
			'The following repositories are left out:',
			'',
			...skipped.map(
				(entry) => `- [${entry.name}](${repoUrl(org, entry.name)}) — ${entry.reason}`,
			),
			'',
		);
	}

	lines.push(
		'Private repositories are not included, and neither are dependencies on software outside',
		'the organisation.',
		'',
	);

	return lines.join('\n');
}

/** The same data as the page, for anyone who would rather query than read. */
export function renderJson(graph: Graph): string {
	return `${JSON.stringify(graph, null, '\t')}\n`;
}
