/**
 * Renders the collected graph as a VitePress page.
 *
 * Diagrams carry no hard-coded colours: vitepress-plugin-mermaid swaps the
 * mermaid theme with the site's light and dark mode, and any colour set here
 * would survive that switch and break the contrast in one of the two.
 * Dependency kinds are therefore told apart by arrow style and by having a
 * diagram of their own.
 */

import { EDGE_KIND_META, EDGE_KINDS, type Edge, type EdgeKind, type Graph } from './model';
import { CONFIG_PATH } from './config';

/** Mermaid identifiers allow far less than repository names do. */
function nodeId(repo: string): string {
	return `r_${repo.replace(/[^A-Za-z0-9]/g, '_')}`;
}

function repoUrl(org: string, repo: string): string {
	return `https://github.com/${org}/${repo}`;
}

function sourceUrl(org: string, edge: Edge, defaultBranch: string): string {
	const line = edge.line > 0 ? `#L${edge.line}` : '';
	return `${repoUrl(org, edge.from)}/blob/${defaultBranch}/${edge.path}${line}`;
}

/** Escapes the characters that would break out of a Markdown table cell. */
function cell(text: string): string {
	return text.replace(/\|/g, '\\|');
}

function table(headers: string[], rows: string[][]): string[] {
	return [
		`| ${headers.join(' | ')} |`,
		`| ${headers.map(() => '---').join(' | ')} |`,
		...rows.map((row) => `| ${row.join(' | ')} |`),
	];
}

/** The strongest kind linking a pair of repositories decides how it is drawn. */
function strongestKind(edges: Edge[]): EdgeKind {
	return edges.reduce((strongest, edge) =>
		EDGE_KIND_META[edge.kind].weight > EDGE_KIND_META[strongest.kind].weight ? edge : strongest,
	).kind;
}

function groupEdges(edges: Edge[]): Map<string, Edge[]> {
	const pairs = new Map<string, Edge[]>();
	for (const edge of edges) {
		const key = `${edge.from} ${edge.to}`;
		const bucket = pairs.get(key);
		if (bucket) bucket.push(edge);
		else pairs.set(key, [edge]);
	}
	return pairs;
}

/** The overview: every repository, inside its group, with one arrow per pair. */
function overviewDiagram(graph: Graph): string[] {
	const lines = ['```mermaid', 'flowchart LR'];

	for (const group of graph.groups) {
		const members = graph.repos.filter((repo) => repo.group === group.id);
		if (members.length === 0) continue;
		lines.push(`  subgraph ${nodeId(group.id)}_g["${group.title}"]`);
		lines.push('    direction LR');
		for (const repo of members) lines.push(`    ${nodeId(repo.name)}["${repo.name}"]`);
		lines.push('  end');
	}

	for (const [key, edges] of groupEdges(graph.edges)) {
		const [from, to] = key.split(' ');
		lines.push(`  ${nodeId(from)} ${EDGE_KIND_META[strongestKind(edges)].arrow} ${nodeId(to)}`);
	}

	lines.push('```');
	return lines;
}

/** One diagram per kind, showing only the repositories that kind connects. */
function kindDiagram(edges: Edge[], kind: EdgeKind): string[] {
	const lines = ['```mermaid', 'flowchart LR'];

	for (const repo of [...new Set(edges.flatMap((edge) => [edge.from, edge.to]))].sort()) {
		lines.push(`  ${nodeId(repo)}["${repo}"]`);
	}
	for (const key of groupEdges(edges).keys()) {
		const [from, to] = key.split(' ');
		lines.push(`  ${nodeId(from)} ${EDGE_KIND_META[kind].arrow} ${nodeId(to)}`);
	}

	lines.push('```');
	return lines;
}

export interface RenderOptions {
	graph: Graph;
	/** Default branch per repository, for the evidence links. */
	branches: Map<string, string>;
	/** Repositories the org has but the graph leaves out, with the reason. */
	skipped: { name: string; reason: string }[];
}

export function renderPage({ graph, branches, skipped }: RenderOptions): string {
	const { org } = graph;
	const lines: string[] = [
		'<!-- Generated by scripts/build-dependency-graph.ts — do not edit. -->',
		'',
		'# Repository dependencies',
		'',
		'> [!NOTE]',
		'> This page is generated from the public repositories of the',
		`> [${org}](https://github.com/${org}) organisation. To correct or extend it, change`,
		`> [\`${CONFIG_PATH}\`](https://github.com/${org}/versatiles-documentation/blob/main/${CONFIG_PATH})`,
		'> or the repository it describes — edits made here are overwritten.',
		'',
		'VersaTiles is not one program but a few dozen repositories that build on each other:',
		'a Rust core, npm packages, Docker images, tile-generation pipelines and the sites that',
		'serve the result. Those links are easy to lose track of, because they are written down',
		'in a different place every time — a `package.json` here, a `FROM` line there, a `curl`',
		'in a shell script somewhere else.',
		'',
		'This page collects all of them in one diagram.',
		'',
		'## How to read the diagrams',
		'',
		'An arrow points **from a repository to what it depends on**, so the arrows of the core',
		'components point away from them and the most heavily used repositories are the ones',
		'everything else aims at. The arrow style says how the dependency is expressed:',
		'',
	];

	// Kinds that share an arrow share a legend row, so the table never claims a
	// distinction the diagram cannot show.
	const byArrow = new Map<string, EdgeKind[]>();
	for (const kind of EDGE_KINDS) {
		const arrow = EDGE_KIND_META[kind].arrow;
		byArrow.set(arrow, [...(byArrow.get(arrow) ?? []), kind]);
	}
	lines.push(
		...table(
			['Arrow', 'Meaning'],
			[...byArrow].map(([arrow, kinds]) => [
				`\`${arrow}\``,
				`${kinds.map((kind) => `**${EDGE_KIND_META[kind].title}**`).join(' / ')} — ` +
					kinds.map((kind) => EDGE_KIND_META[kind].summary).join(' '),
			]),
		),
	);

	lines.push(
		'',
		'Where two repositories are connected in more than one way, the overview draws the',
		'strongest link only; the sections further down show each kind on its own.',
		'',
		'## Overview',
		'',
		...overviewDiagram(graph),
		'',
		'## Repositories',
		'',
	);

	const dependsOn = new Map<string, Set<string>>();
	const usedBy = new Map<string, Set<string>>();
	for (const edge of graph.edges) {
		if (!dependsOn.has(edge.from)) dependsOn.set(edge.from, new Set());
		if (!usedBy.has(edge.to)) usedBy.set(edge.to, new Set());
		dependsOn.get(edge.from)?.add(edge.to);
		usedBy.get(edge.to)?.add(edge.from);
	}

	for (const group of graph.groups) {
		const members = graph.repos.filter((repo) => repo.group === group.id);
		if (members.length === 0) continue;
		lines.push(`### ${group.title}`, '', group.summary, '');
		lines.push(
			...table(
				['Repository', 'Description', 'Depends on', 'Used by'],
				members.map((repo) => [
					`[${repo.name}](${repoUrl(org, repo.name)})`,
					cell(repo.description ?? '—'),
					String(dependsOn.get(repo.name)?.size ?? 0),
					String(usedBy.get(repo.name)?.size ?? 0),
				]),
			),
			'',
		);
	}

	for (const kind of EDGE_KINDS) {
		const edges = graph.edges.filter((edge) => edge.kind === kind);
		if (edges.length === 0) continue;
		const meta = EDGE_KIND_META[kind];
		lines.push(`## ${meta.title}`, '', meta.summary, '', ...kindDiagram(edges, kind), '');

		lines.push(`::: details Where these ${edges.length} links come from`, '');
		lines.push(
			...table(
				['From', 'To', 'Found', 'Source'],
				edges.map((edge) => [
					edge.from,
					edge.to,
					`\`${cell(edge.detail)}\``,
					edge.path
						? `[${cell(edge.path)}](${sourceUrl(org, edge, branches.get(edge.from) ?? 'main')})`
						: `\`${CONFIG_PATH}\``,
				]),
			),
		);
		lines.push('', ':::', '');
	}

	lines.push(
		'## How this page is made',
		'',
		'`scripts/build-dependency-graph.ts` reads the public repositories of the organisation',
		'and looks for dependencies in the places they are actually declared: `package.json`,',
		'`Cargo.toml`, `Dockerfile`s, GitHub Actions workflows, and build or install scripts that',
		'fetch release assets. Markdown is deliberately not searched — README badges and prose',
		'links mention half the organisation and say nothing about what a build needs.',
		'',
		'Every arrow therefore has a file and a line behind it, listed in the tables above and',
		'available as machine-readable data at',
		`[\`/dependency-graph.json\`](/dependency-graph.json). What no parser can see —`,
		'operational dependencies, for instance — is declared by hand in',
		`[\`${CONFIG_PATH}\`](https://github.com/${org}/versatiles-documentation/blob/main/${CONFIG_PATH}),`,
		'which is also where false positives are filtered out and repositories are assigned to',
		'the groups above.',
		'',
	);

	if (skipped.length > 0) {
		lines.push(
			'The following repositories are left out:',
			'',
			...skipped.map(
				(entry) => `- [${entry.name}](${repoUrl(org, entry.name)}) — ${entry.reason}`,
			),
			'',
		);
	}

	lines.push(
		'Private repositories are not included, and neither are dependencies on software outside',
		'the organisation.',
		'',
	);

	return lines.join('\n');
}

/** The same data as the page, for anyone who would rather query than read. */
export function renderJson(graph: Graph): string {
	return `${JSON.stringify(graph, null, '\t')}\n`;
}
